[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-dockerfile"
description = "Dockerfile grammar for tree-sitter"
version = "0.3.0"
keywords = ["incremental", "parsing", "tree-sitter", "dockerfile"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed"
]
authors = [{ name = "Camden Cheek", email = "camden@ccheek.com" }, { name = "SJ", email = "suresh@robotpajamas.com" }]
requires-python = ">=3.10"
license.text = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/sureshjoshi/tree-sitter-dockerfile"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
